<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RE35JDP4" failures="1" tests="10" name="Test" time="70.565" errors="0" timestamp="10 Mar 2024 13:54:15 GMT">
  <testcase classname="com.sqa.qa.testcases.CustomerLoginTest" name="customerlogin" time="1.61"/>
  <testcase classname="com.sqa.qa.testcases.TransactionsPageTest" name="Verify_Deposit_With_ValideAmmount" time="1.812"/>
  <testcase classname="com.sqa.qa.testcases.AccountPageTest" name="Verify_Deposit_With_ValideAmmount" time="2.144"/>
  <testcase classname="com.sqa.qa.testcases.AddCustomerTest" name="AddCustomer_NotExist" time="1.292"/>
  <testcase classname="com.sqa.qa.testcases.OpenAccountPageTest" name="OpenAccount" time="2.076"/>
  <testcase classname="com.sqa.qa.testcases.CustomersPageTest" name="DeleteCustomerEntry" time="0.865"/>
  <testcase classname="com.sqa.qa.testcases.AccountPageTest" name="Verify_Deposit_With_InValideAmmount" time="1.2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.sqa.qa.pages.AccountPage.InValidDeposit(AccountPage.java:179)
	at com.sqa.qa.testcases.AccountPageTest.Verify_Deposit_With_InValideAmmount(AccountPageTest.java:44)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Verify_Deposit_With_InValideAmmount -->
  <testcase classname="com.sqa.qa.testcases.AddCustomerTest" name="AddCustomer_Exist" time="1.948"/>
  <testcase classname="com.sqa.qa.testcases.AccountPageTest" name="Verify_Withdraw_With_ValideAmmount" time="11.934"/>
  <testcase classname="com.sqa.qa.testcases.AccountPageTest" name="Verify_Withdraw_With_InSufficient" time="12.144"/>
</testsuite> <!-- Test -->
